export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/HXzfssQ/omoda-nl-lsa-XYTh-4g-Q-unsplash.jpg",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/K5wLKKy/khalid-boutchich.jpg",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/MN4Wzz5/ussama-azam-xg-NSlx7-Dj-YM-unsplash.jpg",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const users = [
  {
    name: "John",
    email: "admin@example.com",
    password: "123456",
    isAdmin: true,
  },
  {
    name: "Jane",
    email: "user@example.com",
    password: "123456",
    isAdmin: false,
  },
];

export const products = [
  {
    name: "Poplin Shirt",
    slug: "poplin-shirt",
    category: "Shirts",
    image:
      "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    price: 70,
    brand: "Prada",
    rating: 4.5,
    numReviews: 8,
    countInStock: 20,
    description: "A popular shirt",
    },
    {
    name: "Lacoste Shirt",
    slug: "lacoste-shirt",
    category: "Shirts",
    image:
      "https://i.ibb.co/232zSdm/shirt1.jpg",
    price: 70,
    brand: "Lacoste",
    rating: 4.5,
    numReviews: 8,
    countInStock: 20,
    description: "A popular shirt",
  },
  {
    name: "Dress",
    slug: "dress",
    category: ["Dress", "women"],
    image:
      "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    price: 80,
    brand: "Adidas",
    rating: 3.2,
    numReviews: 10,
    countInStock: 20,
    description: "A popular dress",
  },
  {
    name: "Women Coat",
    slug: "women-coat",
    category: ["coat", "women", "khaki"],
    image:
      "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    price: 90,
    brand: "J. Crew",
    rating: 4.5,
    numReviews: 3,
    countInStock: 20,
    description: "A popular coat",
    size: ["L", "M", "S"],
  },
  {
    name: "Golf Pants",
    slug: "golf-pants",
    category: "Pants",
    image: "https://i.ibb.co/7WHvnYy/pants1.jpg",
    price: 90,
    brand: "Oliver",
    rating: 2.9,
    numReviews: 13,
    countInStock: 20,
    description: "Smart looking pants",
  },
  {
    name: "Fit Pants",
    slug: "fit-pants",
    category: "Pants",
    image: "https://i.ibb.co/HGrnBSb/pants2.jpg",
    price: 95,
    brand: "Zara",
    rating: 3.5,
    numReviews: 7,
    countInStock: 20,
    description: "A popular pants",
  },
  {
    name: "Classic Pants",
    slug: "classic-pants",
    category: "Pants",
    image: "https://i.ibb.co/fD1y2p3/pants3.jpg",
    price: 75,
    brand: "Casely",
    rating: 2.4,
    numReviews: 14,
    countInStock: 20,
    description: "A popular pants",
  },
];
